spring:
  application:
    name: w1

  data:
    mongodb:
      host: localhost
      database: writeConcernDb

mongock:
  enabled: true
  migration-scan-package:
    - mongock.writeConcern.w1.changeLog
  lock-repository-name: mongock.changeLog.lock
  migration-repository-name: mongock.changeLog.history
  # Cannot resolve configuration property 'mongock.transaction-enabled' but it still works just fine
  transaction-enabled: false
  #runner-type: InitializingBean

  mongo-db:
    read-concern: local
    read-preference: primary
    write-concern:
      w: 1

